### ISSUE TITLE
Transition Animation between views

### ISSUE THREAD

**Issue by scheng82** [bmeikle56/TransACT#46]
Fix the view transition animation

**Comment by scheng82** [comment]
Digging a little bit into this problem: unfortunately, `NavigationView/NavigationLink` doesn't support custom transition animations. There's a `NavigationStack` package someone put online that supports some custom transitions, but we will have to refactor our code to use this `NavigationStack`. Not sure about the potential problem of switching to it. Planning to push this problem for now.
https://betterprogramming.pub/a-flexible-swiftui-navigation-library-f3d28e75a506

**Comment by kuaikuaikk** [comment]
I researched on that last week. Yes, I think we need to use `NavigationStack` instead. There will be more work to do than I thought.

**Comment by scheng82** [comment]
> Digging a little bit into this problem: unfortunately, `NavigationView/NavigationLink` doesn't support custom transition animations. There's a `NavigationStack` package someone put online that supports some custom transitions, but we will have to refactor our code to use this `NavigationStack`. Not sure about the potential problem of switching to it. Planning to push this problem for now. https://betterprogramming.pub/a-flexible-swiftui-navigation-library-f3d28e75a506
