### ISSUE TITLE
MapBoxMapView.swift fixes

### ISSUE THREAD

**Issue by bmeikle56** [bmeikle56/TransACT#66]
- I am not sure what the checkSurvey() function is for/where the code was gotten from/what it does
- The MapBoxMapView.swift file should have the Firebase code moved to FirebaseManager if possible to keep the consistency and contain all the Firebase code in one spot as well as reducing the amount of imports
- We could move the other Mapbox functions that were found online to a new MapboxManager class to keep consistency with the project and also because the MapBoxMapView class should only be concerning the view and any backend functions should be stored elsewhere if possible

**Comment by kuaikuaikk** [comment]
We can delete checkSurvey() now since we already have survey manager
